name: Blockie Linux

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
            - run: sudo apt install -y build-essential cmake g++ libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev 
            - name: Build game
            - run: mkdir build && cd build && cmake .. && make